---
apiVersion: v1
kind: Namespace
metadata:
  name: codeserver-ns
  labels:
    app: codeserver

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-pvc
  namespace: codeserver-ns
  labels:
    app: codeserver
    name: codeserver-pvc
spec:
  storageClassName: do-block-storage ## k get sc (storage class)
  accessModes: [ ReadWriteOnce ] ## https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  resources:
    requests:
      storage: 1Gi  ## k get pvc,pv -nplayground, k describe -nplayground pvc/mysql-pvc

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codeserver-cm
  namespace: codeserver-ns
  labels:
    app: codeserver
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: codeserver.188.166.204.182.nip.io

---
apiVersion: v1
kind: Secret
metadata:
  name: codeserver-secret
  namespace: codeserver-ns
  labels:
    app: codeserver
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver-deployment
  namespace: codeserver-ns
  labels:
    app: codeserver
    name: codeserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver
      name: codeserver-po
  template:
    metadata:
      name: codeserver-po
      labels:
        app: codeserver
        name: codeserver-po
    spec:
      volumes:
      - name: workspace-vol
        persistentVolumeClaim:
          claimName: codeserver-pvc
      containers:
      - name: codeserver-containers
        image: linuxserver/code-server:4.18.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: codeserver-cm
        - secretRef:
            name: codeserver-secret
        ports:
        - containerPort: 8443 
        volumeMounts:
        - name: workspace-vol
          mountPath: /config/workspace

---
apiVersion: v1
kind: Service
metadata:
  name: codeserver-svc
  namespace: codeserver-ns
  labels:
    app: codeserver
    name: codeserver-svc
spec:
  type: ClusterIP
  selector:
    app: codeserver
    name: codeserver-po
  ports:
  - port: 8443
    targetPort: 8443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codeserver-ing
  namespace: codeserver-ns
  labels:
    app: codeserver
    name: codeserver-ing
spec:
  ingressClassName: nginx
  rules:
  - host: codeserver.188.166.204.182.nip.io ## get  External IP from kubectl get svc -ningress-nginx
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: codeserver-svc
            port:
              number: 8443